version: '3'

services:
  kaiapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kai-docker
    container_name: kaiapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env 
    environment:
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      GMAIL_ACCOUNT: ${GMAIL_ACCOUNT}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGODB_URI}
  