@echo off
echo Iniciando el servidor... 
docker-compose up -d
echo El servidor se esta iniciando. Puede ver el estado desde Docker Desktop... 
echo Puede cerrar esta ventana. Presione cualquier tecla para salir.
pause >nul